---

# If you don't specify remote_user in Ansible playbook or inventory
# ansible relies on ssh to make the connection, so the only way to know username
# is to parse ssh config files or specify it here - which is way simpler for a one shot

# These are examples of settings for your convenience.

rhis_user: "ansiblerunner"   # required if using vault_files_list
remote_path: "/home/{{ rhis_user }}/.rhis_dir " # remote_path is normally specified as an extra variable
# -e "remote_path=/home/ansiblerunner/.my_private_dir"

vault_files_list:
  - ~/rhisbuilder_vault.yml
  # - ~/vault/rhis_builder_idm_vault.yml
#  - ~/vault/rhis_builder_aap_vault.yml
#  - ~/vault/rhis_builder_nbde_vault.yml
#  - ~/vault/rhis_builder_pipelines_vault.yml
#  - ~/vault/rhis_builder_yubikey_vault.yml
