---
# variables required for idm_pre

rhc_insights_state: "absent"
rhc_enable_auto_update: false

repository_ids:
  - "rhel-{{ ansible_distribution_major_version }}-for-x86_64-baseos-rpms"
  - "rhel-{{ ansible_distribution_major_version }}-for-x86_64-appstream-rpms"
  - "rhel-{{ ansible_distribution_major_version }}-for-x86_64-supplementary-rpms"
  - "satellite-client-6-for-rhel-{{ ansible_distribution_major_version }}-x86_64-rpms"

timeserver1: "time.nrc.ca"
timeserver2: "time.chu.nrc.ca"

ipa_firewalld_zone: "public"
# interface supporting the default ipv4 address
ipa_prime_interface: "{{ ansible_interfaces | map('regex_replace', '^', 'ansible_') | map('extract', vars) | selectattr('ipv4', 'defined') | selectattr('ipv4.address', 'match', ansible_default_ipv4.address) | map(attribute='device') | first }}" # noqa yaml[line-length]
ipa_firewalld_services:
  - freeipa-4
  - freeipa-ldap
  - freeipa-ldaps
  - freeipa-replication
  - freeipa-trust

ipa_required_umask: "0022"
ipa_crypto_policy: "DeFaULt"
# ipa_crypto_policy: "FuturE"

# add any other hosts that you need to resolve
# before IdM DNS comes up in your network here
# These are simply test values
etc_hosts_list:
  - ip: "192.168.64.6"
    fqdn: "rhis-provisioner.shawking.ca"
  - ip: "192.168.52.11"
    fqdn: "satellite.shawking.ca"
