---
# This contains all the definitions for Content Views and Composite Content Views
# It defines the filters and filter rules for the content views as well

errata_end_date: "{{ ansible_date_time.date }}"
skip_publish_all: false

# These content views are needed to build the environment or run a workflow.
# Do not remove them. You will want them anyway.
# You can always copy one, paste it into user and modify the repos and filters to test new ones
# Where a CV is only used in conjunction with another CV in a composite, it is only published to Library

content_views:

# AAP Files for installing the Ansible Nodes for the RH-ISAM
  - name: "AAP24_Files"
    desc: "Red Hat Ansible Automation Platform Install Files"
    org: "{{ satellite_organization }}"
    force_publish: false
    publication_threshold_hours: 24
    repositories:
      - name: "Red Hat Ansible Automation Platform 2.4 for RHEL 9 x86_64 Files"
        product: "Red Hat Ansible Automation Platform"
    environments:
      - "Library"

  - name: "AAP24_RPMs"
    desc: "Red Hat Ansible Automation Platform Install RPMs"
    org: "{{ satellite_organization }}"
    force_publish: false
    publication_threshold_hours: 24
    repositories:
      - name: "Red Hat Ansible Automation Platform 2.4 for RHEL 9 x86_64 RPMs"
        product: "Red Hat Ansible Automation Platform"
    environments:
      - "Library"

  - name: "AAP25_Files"
    desc: "Red Hat Ansible Automation Platform Install Files"
    org: "{{ satellite_organization }}"
    force_publish: false
    publication_threshold_hours: 24
    repositories:
      - name: "Red Hat Ansible Automation Platform 2.5 for RHEL 9 x86_64 Files"
        product: "Red Hat Ansible Automation Platform"
    environments:
      - "Library"

  - name: "AAP25_RPMs"
    desc: "Red Hat Ansible Automation Platform Install RPMs"
    org: "{{ satellite_organization }}"
    force_publish: false
    publication_threshold_hours: 24
    repositories:
      - name: "Red Hat Ansible Automation Platform 2.5 for RHEL 9 x86_64 RPMs"
        product: "Red Hat Ansible Automation Platform"
    environments:
      - "Library"

# RHEL8 for lots of things
  - name: "SOE8"
    desc: "Red Hat Enterprise Linux 8 Standard Operating Environment Content"
    org: "{{ satellite_organization }}"
    force_publish: false
    publication_threshold_hours: 24
    repositories:
      - name: "Red Hat Enterprise Linux 8 for x86_64 - AppStream RPMs 8"
        product: "Red Hat Enterprise Linux for x86_64"
      - name: "Red Hat Enterprise Linux 8 for x86_64 - BaseOS RPMs 8"
        product: "Red Hat Enterprise Linux for x86_64"
      - name: "Red Hat Enterprise Linux 8 for x86_64 - AppStream Kickstart 8.10"
        product: "Red Hat Enterprise Linux for x86_64"
      - name: "Red Hat Enterprise Linux 8 for x86_64 - BaseOS Kickstart 8.10"
        product: "Red Hat Enterprise Linux for x86_64"
      - name: "Red Hat Satellite Client 6 for RHEL 8 x86_64 RPMs"
        product: "Red Hat Enterprise Linux for x86_64"
    filters:
      - name: "Include_All_Packages_No_Errata"
        type: "rpm"
        inclusion: true
        description: "Include all rpms with no errata for all repositories"
        original_packages: true
        repositories: "[]"
      - name: "Include_All_Streams_No_Errata"
        type: "modulemd"
        inclusion: true
        description: "Include all module streams with no errata for all repositories"
        original_module_streams: true
        repositories: "[]"
      - name: "Include_Errata_By_Date"
        type: "erratum"
        inclusion: true
        description: "Include all errata updated as of {{ errata_end_date }}"
        repositories: "[]"
        rules:
          - name: "errata-by-date-{{ errata_end_date }}"
            end_date: "{{ errata_end_date }}"
            date_type: "updated"
            types:
              - "enhancement"
              - "bugfix"
              - "security"
      - name: "Exclude_FireFox"
        type: "rpm"
        inclusion: false
        description: "Do not provide Firefox to servers"
        repositories: "[]"
        rules:
          - name: "firefox*"
            basearch: "x86_64"
    date_filter_name: "Include_Errata_By_Date"
    environments:
      - "Library"
      - "Development"
      - "Production"

# SOE_RHEL9_x86_64 - the new RHEL 8 :-)
  - name: "SOE9"
    desc: "Red Hat Enterprise Linux 9 x86_64 Standard Operating Environment Content"
    org: "{{ satellite_organization }}"
    force_publish: false
    publication_threshold_hours: 24
    repositories:
      - name: "Red Hat Enterprise Linux 9 for x86_64 - AppStream RPMs 9"
        product: "Red Hat Enterprise Linux for x86_64"
      - name: "Red Hat Enterprise Linux 9 for x86_64 - BaseOS RPMs 9"
        product: "Red Hat Enterprise Linux for x86_64"
      - name: "Red Hat Enterprise Linux 9 for x86_64 - Supplementary RPMs 9"
        product: "Red Hat Enterprise Linux for x86_64"
      - name: "Red Hat Enterprise Linux 9 for x86_64 - AppStream Kickstart 9.5"
        product: "Red Hat Enterprise Linux for x86_64"
      - name: "Red Hat Enterprise Linux 9 for x86_64 - BaseOS Kickstart 9.5"
        product: "Red Hat Enterprise Linux for x86_64"
      - name: "Red Hat Satellite Client 6 for RHEL 9 x86_64 RPMs"
        product: "Red Hat Enterprise Linux for x86_64"
    filters:
      - name: "Include_All_Packages_No_Errata"
        type: "rpm"
        inclusion: true
        description: "Include all rpms with no errata for all repositories"
        original_packages: true
        repositories: "[]"
      - name: "Include_All_Streams_No_Errata"
        type: "modulemd"
        inclusion: true
        description: "Include all module streams with no errata for all repositories"
        original_module_streams: true
        repositories: "[]"
      - name: "Include_Errata_By_Date"
        type: "erratum"
        inclusion: true
        description: "Include all errata updated as of {{ errata_end_date }}"
        repositories: "[]"
        rules:
          - name: "errata-by-date-{{ errata_end_date }}"
            end_date: "{{ errata_end_date }}"
            date_type: "updated"
            types:
              - "enhancement"
              - "bugfix"
              - "security"
      - name: "Exclude_FireFox"
        type: "rpm"
        inclusion: false
        description: "Do not provide Firefox to servers"
        repositories: "[]"
        rules:
          - name: "firefox*"
            basearch: "x86_64"
    date_filter_name: "Include_Errata_By_Date"
    environments:
      - "Library"
      - "Development"
      - "Production"

# These are the composite content views necessary for the RH-ISAM
composite_content_views:
  - name: "SOE_AAP24"
    desc: "SOE for Ansible Automation Platform 2.4 Servers"
    org: "{{ satellite_organization }}"
    force_publish: false
    publication_threshold_hours: 24
    components:
      - content_view: "SOE9"
        latest: true
      - content_view: "AAP24_Files"
        latest: true
      - content_view: "AAP24_RPMs"
        latest: true
    environments:
      - "Library"
      - "Development"

  - name: "SOE_AAP25"
    desc: "SOE for Ansible Automation Platform 2.5 Servers"
    org: "{{ satellite_organization }}"
    force_publish: false
    publication_threshold_hours: 24
    components:
      - content_view: "SOE9"
        latest: true
      - content_view: "AAP25_Files"
        latest: true
      - content_view: "AAP25_RPMs"
        latest: true
    environments:
      - "Library"
      - "Development"
