---

satellite_hostgroups:
  - name: "hg_x86_64_rhel8_metal"
    description: "RHEL 8 SOE base hostgroup"
    activation_keys: "SOE8_dev"
    ansible_roles:
      - theforeman.foreman_scap_client
    architecture: "x86_64"
    content_source: "satellite.shawking.ca"
    content_view: "SOE8"
    domain: "{{ satellite_domain }}"
    lifecycle_environment: "Development"
    kickstart_repository: "Red Hat Enterprise Linux 8 for x86_64 - BaseOS Kickstart 8.10"
    locations: "{{ satellite_location }}"
    organization: "{{ satellite_organization }}"
    openscap_capsule: "{{ satellite_fqdn }}"
    operatingsystem: "RHEL 8.10"
    ptable: "RHEL_Server_Compliance"
    pxe_loader: "Grub2 UEFI"
    realm: "{{ satellite_domain | upper }}"
    subnet: "shawking.ca"
    root_pass: "{{ satellite_admin_password }}"
    parameters:
      - name: "boot_disk"
        hidden_value: false
        parameter_type: "string"
        value: "/dev/nvme0n1"
      - name: "root_disk"
        hidden_value: false
        parameter_type: "string"
        value: "/dev/nvme0n1"

  - name: "hg_x86_64_rhel9_metal"
    description: "RHEL 9 SOE baremetal hostgroup"
    activation_keys: "SOE9_dev"
    ansible_roles:
      - theforeman.foreman_scap_client
    architecture: "x86_64"
    content_source: "satellite.shawking.ca"
    content_view: "SOE9"
    domain: "{{ satellite_domain }}"
    lifecycle_environment: "Development"
    kickstart_repository: "Red Hat Enterprise Linux 9 for x86_64 - BaseOS Kickstart 9.5"
    locations: "{{ satellite_location }}"
    organization: "{{ satellite_organization }}"
    openscap_capsule: "{{ satellite_fqdn }}"
    operatingsystem: "RHEL 9.5"
    ptable: "RHEL_Server_Compliance"
    pxe_loader: "Grub2 UEFI"
    realm: "{{ satellite_domain | upper }}"
    subnet: "shawking.ca"
    root_pass: "{{ satellite_admin_password }}"
    parameters:
      - name: "boot_disk"
        hidden_value: false
        parameter_type: "string"
        value: "/dev/nvme0n1"
      - name: "root_disk"
        hidden_value: false
        parameter_type: "string"
        value: "/dev/nvme0n1"
