---

# For all of our Red Hat Products and Custom products,
# the repositories are created along with the repository set or custom product

# In day 0 operations, we use this to Override download_policy defaults, set content_credentials, etc.. as an example
# In day 2 operations, we can use this to add and remove repos from our products.

# The following are some examples.
# For custom products we can set these via the product definition as well

satellite_repositories:
  - name: "Red Hat Enterprise Linux 8 for x86_64 - AppStream Kickstart 8.10"
    product: "Red Hat Enterprise Linux for x86_64"
    content_type: "yum"
    download_policy: "on_demand"
  # - name: "Red Hat Enterprise Linux 8 for x86_64 - AppStream RPMs 8"
  #   product: "Red Hat Enterprise Linux for x86_64"
  #   content_type: "yum"
  #   download_policy: "on_demand"
  - name: "Red Hat Enterprise Linux 8 for x86_64 - AppStream RPMs 8.10"
    product: "Red Hat Enterprise Linux for x86_64"
    content_type: "yum"
    download_policy: "on_demand"
  - name: "Red Hat Enterprise Linux 8 for x86_64 - BaseOS Kickstart 8.10"
    product: "Red Hat Enterprise Linux for x86_64"
    content_type: "yum"
    download_policy: "on_demand"
  # - name: "Red Hat Enterprise Linux 8 for x86_64 - BaseOS RPMs 8"
  #   product: "Red Hat Enterprise Linux for x86_64"
  #   content_type: "yum"
  #   download_policy: "on_demand"
  - name: "Red Hat Enterprise Linux 8 for x86_64 - BaseOS RPMs 8.10"
    product: "Red Hat Enterprise Linux for x86_64"
    content_type: "yum"
    download_policy: "on_demand"
  # - name: "Red Hat Enterprise Linux 9 for x86_64 - AppStream Kickstart 9.4"
  #   product: "Red Hat Enterprise Linux for x86_64"
  #   content_type: "yum"
  #   download_policy: "on_demand"
  - name: "Red Hat Enterprise Linux 9 for x86_64 - AppStream Kickstart 9.5"
    product: "Red Hat Enterprise Linux for x86_64"
    content_type: "yum"
    download_policy: "on_demand"
  - name: "Red Hat Enterprise Linux 9 for x86_64 - AppStream RPMs 9"
    product: "Red Hat Enterprise Linux for x86_64"
    content_type: "yum"
    download_policy: "on_demand"
  # - name: "Red Hat Enterprise Linux 9 for x86_64 - AppStream RPMs 9.4"
  #   product: "Red Hat Enterprise Linux for x86_64"
  #   content_type: "yum"
  #   download_policy: "on_demand"
  # - name: "Red Hat Enterprise Linux 9 for x86_64 - BaseOS Kickstart 9.4"
  #   product: "Red Hat Enterprise Linux for x86_64"
  #   content_type: "yum"
  #   download_policy: "on_demand"
  - name: "Red Hat Enterprise Linux 9 for x86_64 - BaseOS Kickstart 9.5"
    product: "Red Hat Enterprise Linux for x86_64"
    content_type: "yum"
    download_policy: "on_demand"
  - name: "Red Hat Enterprise Linux 9 for x86_64 - BaseOS RPMs 9"
    product: "Red Hat Enterprise Linux for x86_64"
    content_type: "yum"
    download_policy: "on_demand"
  # - name: "Red Hat Enterprise Linux 9 for x86_64 - BaseOS RPMs 9.4"
  #   product: "Red Hat Enterprise Linux for x86_64"
  #   content_type: "yum"
  #   download_policy: "on_demand"
  - name: "Red Hat Satellite Client 6 for RHEL 8 x86_64 RPMs"
    product: "Red Hat Enterprise Linux for x86_64"
    content_type: "yum"
    download_policy: "on_demand"
  - name: "Red Hat Satellite Client 6 for RHEL 9 x86_64 RPMs"
    product: "Red Hat Enterprise Linux for x86_64"
    content_type: "yum"
    download_policy: "on_demand"
  - name: "Red Hat Satellite Maintenance 6.16 for RHEL 8 x86_64 RPMs"
    product: "Red Hat Enterprise Linux for x86_64"
    content_type: "yum"
    download_policy: "on_demand"
  # - name: "Red Hat Enterprise Linux 9 for ARM 64 - AppStream Kickstart 9.4"
  #   product: "Red Hat Enterprise Linux for ARM 64"
  #   content_type: "yum"
  #   download_policy: "on_demand"
  # - name: "Red Hat Enterprise Linux 9 for ARM 64 - AppStream RPMs 9"
  #   product: "Red Hat Enterprise Linux for ARM 64"
  #   content_type: "yum"
  #   download_policy: "on_demand"
  # - name: "Red Hat Enterprise Linux 9 for ARM 64 - BaseOS Kickstart 9.4"
  #   product: "Red Hat Enterprise Linux for ARM 64"
  #   content_type: "yum"
  #   download_policy: "on_demand"
  # - name: "Red Hat Enterprise Linux 9 for ARM 64 - BaseOS RPMs 9"
  #   product: "Red Hat Enterprise Linux for ARM 64"
  #   content_type: "yum"
  #   download_policy: "on_demand"
  # - name: "Red Hat Satellite Client 6 for RHEL 9 aarch64 RPMs"
  #   product: "Red Hat Enterprise Linux for ARM 64"
  #   content_type: "yum"
  #   download_policy: "on_demand"
